import * as nodePath from 'path';
import { parseEnvFile } from './env-file';

/**
 * Builds the settings file (`hexyrn.env`) a Windows install runs on.
 * Pure function (the CLI in write-runtime-config.ts does the file I/O) so it
 * can be unit-tested, including against the app's own production guard.
 */
export interface RuntimeConfigInput {
  /** Contents of database.env written by generate-credentials.ps1 (secrets + database passwords). */
  credentialsText: string;
  /** The vendor's public licence key (single line base64 or PEM). */
  licencePublicKey: string;
  installDir: string;
  dataDir: string;
  pgPort: number;
  webPort: number;
}

const REQUIRED_CREDENTIALS = [
  'TOTP_MASTER_KEY_CURRENT',
  'SECRET_ENCRYPTION_MASTER_KEY',
  'HEXYRN_SESSION_SECRET',
  'HEXYRN_MIGRATE_DB_PASSWORD',
  'HEXYRN_APP_DB_PASSWORD',
  'HEXYRN_BACKUP_DB_PASSWORD',
] as const;

export function buildRuntimeConfig(
  input: RuntimeConfigInput,
  path: Pick<typeof nodePath, 'join'> = nodePath,
): string {
  const creds = parseEnvFile(input.credentialsText);
  for (const key of REQUIRED_CREDENTIALS) {
    if (!creds[key]) throw new Error(`credentials file is missing ${key}`);
  }
  for (const key of [
    'HEXYRN_MIGRATE_DB_PASSWORD',
    'HEXYRN_APP_DB_PASSWORD',
    'HEXYRN_BACKUP_DB_PASSWORD',
  ]) {
    // These go inside postgres:// URLs unescaped; the generator emits a URL-safe alphabet.
    if (!/^[A-Za-z0-9_-]+$/.test(creds[key]))
      throw new Error(`${key} contains characters that are not URL-safe`);
  }
  const licenceKey = input.licencePublicKey.trim().replace(/\r?\n/g, '\\n');
  if (!licenceKey) {
    throw new Error(
      'no licence public key: this installer was built without one. Rebuild with -LicencePublicKeyFile (see docs/WINDOWS_INSTALLER_DESIGN.md).',
    );
  }
  if (!Number.isInteger(input.webPort) || input.webPort < 1 || input.webPort > 65535)
    throw new Error('invalid web port');
  if (!Number.isInteger(input.pgPort) || input.pgPort < 1 || input.pgPort > 65535)
    throw new Error('invalid PostgreSQL port');

  const db = (role: string, password: string) =>
    `postgres://${role}:${password}@127.0.0.1:${input.pgPort}/hexyrn_core`;
  const p = (...parts: string[]) => path.join(input.installDir, ...parts);
  const d = (...parts: string[]) => path.join(input.dataDir, ...parts);

  const lines: Array<[string, string]> = [
    ['NODE_ENV', 'production'],
    // Loopback only: a single-PC install is not reachable from the network unless the operator changes this.
    ['HOST', '127.0.0.1'],
    ['PORT', String(input.webPort)],
    ['HEXYRN_WEB_DIR', p('api', 'apps', 'web', 'dist')],
    ['DATABASE_URL', db('hexyrn_app', creds.HEXYRN_APP_DB_PASSWORD)],
    ['MIGRATE_DATABASE_URL', db('hexyrn', creds.HEXYRN_MIGRATE_DB_PASSWORD)],
    ['BACKUP_DATABASE_URL', db('hexyrn_backup', creds.HEXYRN_BACKUP_DB_PASSWORD)],
    ['TOTP_MASTER_KEY_CURRENT', creds.TOTP_MASTER_KEY_CURRENT],
    ['SECRET_ENCRYPTION_MASTER_KEY', creds.SECRET_ENCRYPTION_MASTER_KEY],
    ['HEXYRN_SESSION_SECRET', creds.HEXYRN_SESSION_SECRET],
    ['HEXYRN_LICENSE_PUBLIC_KEY', licenceKey],
    ['HEXYRN_PUBLIC_URL', `http://localhost:${input.webPort}`],
    ['ALLOWED_ORIGINS', `http://localhost:${input.webPort},http://127.0.0.1:${input.webPort}`],
    // Browsers treat http://localhost as a secure context and accept Secure cookies there.
    ['COOKIE_SECURE', 'true'],
    ['LOCAL_STORAGE_PATH', d('storage')],
    ['HEXYRN_BACKUP_DIR', d('backups')],
    ['PG_DUMP_PATH', p('postgresql', 'bin', 'pg_dump.exe')],
    ['PG_RESTORE_PATH', p('postgresql', 'bin', 'pg_restore.exe')],
    ['HEXYRN_BOOTSTRAP_TOKEN_FILE', d('config', 'bootstrap-token.txt')],
  ];
  return (
    '# Generated by the Hexyrn installer. Contains SECRETS - do not share or edit unless you know why.\n' +
    lines.map(([k, v]) => `${k}=${v}`).join('\n') +
    '\n'
  );
}
