/**
 * THROW-AWAY TEST KEY - for the automated tests and the local demo seed ONLY.
 *
 * It is committed in full on purpose (so tests are reproducible) and is therefore worthless as a
 * secret. It lives here, under src/vendor-tools/, so that it is NEVER compiled into the
 * application that ships: a customer installation contains no private key of any kind, test or
 * real. The matching public half is platform/licensing/keys.ts's TEST_LICENSE_PUBLIC_KEY_PEM,
 * which the server uses ONLY outside production when HEXYRN_LICENSE_PUBLIC_KEY is unset.
 *
 * The real production private key is generated by Hexyrn with `npm run licence -- keygen`, is held
 * offline, and must never be added to this repository.
 */
export const TEST_LICENSE_PRIVATE_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIEE5oImvlwDwKH6vyjNw4QIebzvBYWVWwjJIdLnQHZca
-----END PRIVATE KEY-----`;
