import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common';
import { Kysely } from 'kysely';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { Database } from '../../db/types';
import { ReportQueryService, ReportQueryDefinition } from '../reporting/report-query.service';
import { DatasetFieldDefinition } from '../reporting/dataset.service';
import { PermissionCheckSubject } from '../../rbac/permission-evaluator';
import { sanitizeForSpreadsheet, toCsv } from './csv-safe';
import { FileService } from '../files/file.service';

export type ExportFormat = 'csv' | 'xlsx' | 'pdf';

const MAX_SYNCHRONOUS_ROWS = 5000; // P2 item 25 - beyond this, callers should route through the background job path instead

export interface PdfBranding {
  organisationName: string;
  reportTitle: string;
  reportingPeriod?: string;
  includeHexyrnAttribution?: boolean;
}

/**
 * Central export framework. P2 item 7. Exports ALWAYS run through
 * ReportQueryService - never a direct application-table query - so every
 * permission/organisation-isolation/field-visibility rule the query engine
 * enforces applies identically to exports. `sanitizeForSpreadsheet`/
 * `csvCell` (csv-safe.ts) defend against CSV/XLSX formula injection in
 * every format that touches a spreadsheet application.
 */
@Injectable()
export class ExportService {
  constructor(
    private readonly queryEngine: ReportQueryService,
    private readonly files: FileService,
  ) {}

  async runQueryForExport(
    db: Kysely<Database>,
    subject: PermissionCheckSubject,
    query: ReportQueryDefinition,
  ): Promise<{
    rows: Record<string, unknown>[];
    dataset: { is_exportable: boolean; fields: unknown };
  }> {
    const dataset = await db
      .selectFrom('dataset_definitions')
      .selectAll()
      .where('dataset_key', '=', query.datasetKey)
      .executeTakeFirst();
    if (!dataset) throw new BadRequestException(`Dataset "${query.datasetKey}" not found.`);
    if (!dataset.is_exportable)
      throw new ForbiddenException(`Dataset "${query.datasetKey}" is not exportable.`);

    const fields = dataset.fields as unknown as DatasetFieldDefinition[];
    const nonExportableRequested = (query.fields ?? []).filter((key) => {
      const field = fields.find((f) => f.key === key);
      return field && field.exportable === false;
    });
    if (nonExportableRequested.length > 0) {
      throw new ForbiddenException(`Field(s) not exportable: ${nonExportableRequested.join(', ')}`);
    }

    const rows = await this.queryEngine.execute(db, subject, {
      ...query,
      limit: Math.min(query.limit ?? MAX_SYNCHRONOUS_ROWS, MAX_SYNCHRONOUS_ROWS),
    });
    return { rows, dataset };
  }

  toCsvBuffer(rows: Record<string, unknown>[], columns: string[]): Buffer {
    return Buffer.from(toCsv(rows, columns), 'utf8');
  }

  async toXlsxBuffer(rows: Record<string, unknown>[], columns: string[]): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Export');
    sheet.addRow(columns.map((c) => sanitizeForSpreadsheet(c)));
    for (const row of rows) {
      sheet.addRow(columns.map((c) => sanitizeForSpreadsheet(row[c])));
    }
    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
  }

  async toPdfBuffer(
    rows: Record<string, unknown>[],
    columns: string[],
    branding: PdfBranding,
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40 });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(16).text(branding.reportTitle, { align: 'left' });
      doc.fontSize(10).fillColor('#555').text(branding.organisationName);
      if (branding.reportingPeriod) doc.text(`Reporting period: ${branding.reportingPeriod}`);
      doc.text(`Generated: ${new Date().toISOString()}`);
      doc.moveDown();

      doc.fillColor('#000').fontSize(9);
      // Deliberately plain-text row rendering (no HTML/script interpretation
      // of report labels/values - P2 item 24's "HTML/script injection in
      // report labels" defense: pdfkit's .text() always renders as literal
      // text, never as markup).
      doc.text(columns.join(' | '), { underline: true });
      for (const row of rows) {
        doc.text(columns.map((c) => String(row[c] ?? '')).join(' | '));
      }

      if (branding.includeHexyrnAttribution !== false) {
        doc
          .moveDown()
          .fontSize(7)
          .fillColor('#999')
          .text('Generated by Hexyrn', { align: 'center' });
      }
      doc.end();
    });
  }

  async recordExportJob(
    db: Kysely<Database>,
    organisationId: string,
    datasetKey: string,
    format: ExportFormat,
    rowCount: number,
    fileRef: string,
    requestedBy?: string,
    serviceAccountId?: string,
  ): Promise<string> {
    const row = await db
      .insertInto('export_jobs')
      .values({
        organisation_id: organisationId,
        requested_by: requestedBy ?? null,
        service_account_id: serviceAccountId ?? null,
        dataset_key: datasetKey,
        format,
        status: 'completed',
        approximate_row_count: rowCount,
        file_ref: fileRef,
        completed_at: new Date() as any,
      })
      .returningAll()
      .executeTakeFirstOrThrow();
    return row.id;
  }
}
